# Generated by Django 4.2.21 on 2025-05-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_productos_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
    ]
