# Generated by Django 4.2.21 on 2025-05-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin Categoria', max_length=50),
        ),
    ]
