# Generated by Django 4.2.21 on 2025-05-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
