# Generated by Django 4.2.21 on 2025-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_usuario',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
