# Generated by Django 4.2.21 on 2025-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_remove_usuarios_id_usuarios_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
