# Generated by Django 4.2.21 on 2025-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_producto_categoria_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
