# Generated by Django 4.2.21 on 2025-05-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'casco'), (1, 'guantes'), (2, 'lentes'), (3, 'destornillador'), (4, 'kit de herramientas'), (5, 'lijadora'), (6, 'llaves'), (7, 'martillo'), (8, 'sierra'), (9, 'taladro'), (10, 'acabados de piso'), (11, 'arena'), (12, 'barnices'), (13, 'cemento'), (14, 'ceramica'), (15, 'ladrillos'), (16, 'pintura')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'epp'), (1, 'herramientas'), (2, 'materiales basicos')], default=0),
        ),
    ]
