# Generated by Django 4.2.21 on 2025-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_producto_tipo_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'epp'), (2, 'herramientas'), (3, 'materiales basicos')], default=0),
        ),
    ]
